In [4]:
import utils as ut
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

pd.__version__
import importlib as il

In [5]:
il.reload(ut)

In [6]:
data = ut.read_data("F:\TFG\datasets\\raw_datasets\datalake.csv")

In [7]:
data

,matchId,id_H,id_A,Div,div_order,Date,season,HomeTeam,AwayTeam,FTHG,...,AHW,B365H,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA
0,0,8,19,D1,0,2000-08-11,T00-01,Dortmund,Hansa Rostock,1,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,20,D1,1,2000-08-12,T00-01,Bayern Munich,Hertha,4,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,15,35,D1,2,2000-08-12,T00-01,Freiburg,Stuttgart,4,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,17,29,D1,3,2000-08-12,T00-01,Hamburg,Munich 1860,2,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,23,4,D1,4,2000-08-12,T00-01,Kaiserslautern,Bochum,0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60000,60000,258,243,SP2,11419,2000-06-04,T99-00,Extremadura,Badajoz,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60001,60001,271,274,SP2,11420,2000-06-04,T99-00,Las Palmas,Levante,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60002,60002,277,314,SP2,11421,2000-06-04,T99-00,Logrones,Villarreal,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60003,60003,288,297,SP2,11422,2000-06-04,T99-00,Osasuna,Recreativo,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60004,60004,300,255,SP2,11423,2000-06-04,T99-00,Salamanca,Eibar,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
COLS_H      = ['matchId','Div','Date','season','id_H','HomeTeam','FTHG','FTAG']
COLS_A      = ['matchId','Div','Date','season','id_A','AwayTeam','FTAG','FTHG']
COLS_AUX    = ['matchId','Div','Date','season','idTeam','Team','FTG','FTG_rival']

data_split = ut.split_data_side(data,COLS_H,COLS_A,COLS_AUX)
data_split.loc[:,"rounds"] = 1
data_split

,matchId,Div,Date,season,idTeam,Team,FTG,FTG_rival,Side,Points,rounds
6408,6408,D1,1993-08-07,T93-94,2,Bayern Munich,3.0,1.0,0,3,1
6408,6408,D1,1993-08-07,T93-94,15,Freiburg,1.0,3.0,1,0,1
6409,6409,D1,1993-08-07,T93-94,8,Dortmund,2.0,1.0,0,3,1
6409,6409,D1,1993-08-07,T93-94,24,Karlsruhe,1.0,2.0,1,0,1
6410,6410,D1,1993-08-07,T93-94,10,Duisburg,2.0,2.0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
27054,27054,F1,2021-05-23,T20-21,114,Lorient,1,1,1,1,1
45755,45755,SP1,2021-05-23,T20-21,203,Granada,0,0,0,1,1
45755,45755,SP1,2021-05-23,T20-21,200,Getafe,0,0,1,1,1
45756,45756,SP1,2021-05-23,T20-21,223,Sevilla,1,0,0,3,1
45756,45756,SP1,2021-05-23,T20-21,185,Alaves,0,1,1,0,1

In [13]:
data_split.groupby(['Div','season']).Date.count().reset_index(level=1).pivot_table(columns='Div',index='season') / 2

         Date
Div        D1     E0     F1     I1    SP1    SP2
season
T00-01  306.0  380.0  306.0  306.0  380.0  462.0
T01-02  306.0  380.0  306.0  306.0  380.0  462.0
T02-03  306.0  380.0  380.0  306.0  380.0  462.0
T03-04  306.0  380.0  380.0  306.0  380.0  462.0
T04-05  306.0  380.0  380.0  380.0  380.0  462.0
T05-06  306.0  380.0  380.0  380.0  380.0  462.0
T06-07  306.0  380.0  380.0  380.0  380.0  462.0
T07-08  306.0  380.0  380.0  380.0  380.0  462.0
T08-09  306.0  380.0  380.0  380.0  380.0  462.0
T09-10  306.0  380.0  380.0  380.0  380.0  462.0
T10-11  306.0  380.0  380.0  380.0  380.0  462.0
T11-12  306.0  380.0  380.0  380.0  380.0  462.0
T12-13  306.0  380.0  380.0  380.0  380.0  462.0
T13-14  306.0  380.0  380.0  380.0  380.0  462.0
T14-15  306.0  380.0  380.0  380.0  380.0  462.0
T15-16  306.0  380.0  380.0  380.0  380.0  462.0
T16-17  306.0  380.0  380.0  380.0  380.0  462.0
T17-18  306.0  380.0  380.0  380.0  380.0  462.0
T18-19  306.0  380.0  380.0  380.0  380.0  462.0
T19-20  306.0  380.0  279.0  380.0  380.0  462.0
T20-21  288.0  350.0  380.0  358.0  380.0  418.0
T93-94  306.0  462.0    NaN  306.0  380.0    NaN
T94-95  306.0  462.0    NaN  306.0  380.0    NaN
T95-96  306.0  380.0    NaN  306.0  462.0    NaN
T96-97  306.0  380.0    NaN  306.0  462.0  380.0
T97-98  306.0  380.0  306.0  306.0  380.0  462.0
T98-99  306.0  380.0  306.0  306.0  380.0  462.0
T99-00  306.0  380.0  306.0  306.0  380.0  462.0

In [19]:
rounds = data_split.sort_values("Date").groupby(["Div","idTeam","season"]).expanding().agg({"rounds":"sum"}).reset_index(drop=False)
rounds.columns = ["Div","idTeam","season","matchId","rounds"]

In [16]:
rounds

        Div  idTeam  season  matchId  rounds
0        D1       0  T06-07     1838     1.0
1        D1       0  T06-07     1846     2.0
2        D1       0  T06-07     1857     3.0
3        D1       0  T06-07     1864     4.0
4        D1       0  T06-07     1873     5.0
...     ...     ...     ...      ...     ...
120005  SP2     317  T20-21    58187    34.0
120006  SP2     317  T20-21    58195    35.0
120007  SP2     317  T20-21    58206    36.0
120008  SP2     317  T20-21    58217    37.0
120009  SP2     317  T20-21    58230    38.0

[120010 rows x 5 columns]