In [1]:
import pandas as pd
import os
from datetime import datetime

In [2]:
path_data = "F:\\TFG\datasets\\football-data\\"
path_raw = "F:\\TFG\\datasets\\raw_datasets\\"

In [3]:
df_concat = pd.DataFrame([])
for s in os.listdir(path_data):
    if '.csv' in s:
        try:
            df = pd.read_csv(path_data + s, sep=',')[['Div','Date','HomeTeam','AwayTeam','FTR','B365D','B365H','B365A']]
            df_concat = pd.concat([df_concat,df],axis=0).reset_index(drop=True)
        except:
            print(s)
            # continue

D1_0001.csv
D1_0102.csv
D1_0203.csv
D1_0304.csv
D1_9394.csv
D1_9495.csv
D1_9596.csv
D1_9697.csv
D1_9798.csv
D1_9899.csv
D1_9900.csv
E0_0001.csv
E0_0102.csv
E0_0304.csv
E0_0506.csv
E0_9394.csv
E0_9495.csv
E0_9596.csv
E0_9697.csv
E0_9798.csv
E0_9899.csv
E0_9900.csv
F1_0001.csv
F1_0102.csv
F1_0203.csv
F1_0304.csv
F1_9798.csv
F1_9899.csv
F1_9900.csv
I1_0001.csv
I1_0102.csv
I1_0304.csv
I1_0405.csv
I1_9394.csv
I1_9495.csv
I1_9596.csv
I1_9697.csv
I1_9798.csv
I1_9899.csv
I1_9900.csv
SP1_0001.csv
SP1_0102.csv
SP1_0405.csv
SP1_9394.csv
SP1_9495.csv
SP1_9596.csv
SP1_9697.csv
SP1_9798.csv
SP1_9899.csv
SP1_9900.csv
SP2_0001.csv
SP2_0102.csv
SP2_0203.csv
SP2_0304.csv
SP2_0708.csv
SP2_9697.csv
SP2_9798.csv
SP2_9899.csv
SP2_9900.csv

In [4]:
df_concat.Date.loc[0]

'06/08/04'

In [5]:
def str2date(d):
    if isinstance(d,float): return None
    try:
        return datetime.strptime(d,"%d/%m/%y")
    except:
        return datetime.strptime(d,"%d/%m/%Y")

In [6]:
df_concat['Date'] = df_concat.Date.apply(str2date)
df_concat = df_concat.dropna()

In [7]:
df_concat['res'] = df_concat.FTR.map({'H':1,'D':0,'A':2})

In [8]:
path_train      = 'F:\\TFG\\datasets\\raw_datasets\\'
raw_Data  = pd.read_csv(path_train+'historical_goals_date'+'.csv',sep=';',decimal=',',index_col='matchId')#.set_index('wyId')


cols = ['FTR',
'FTHG',
'FTAG',
'aux'
]

raw_Data = raw_Data.drop(cols,axis=1,errors='ignore')
raw_Data.sort_index()

raw_Data['year'] = raw_Data.Date.map(lambda x: (datetime.strptime(x,"%Y-%m-%d")).year)

In [9]:
raw_Data = raw_Data[['Date','HomeTeam','AwayTeam']].reset_index()
raw_Data['Date'] = raw_Data.Date.apply(lambda d: datetime.strptime(d,"%Y-%m-%d"))

In [10]:
raw_Data

       matchId       Date    HomeTeam       AwayTeam
0            0 2000-08-19    Charlton       Man City
1            1 2000-08-19     Chelsea       West Ham
2            2 2000-08-19    Coventry  Middlesbrough
3            3 2000-08-19       Derby    Southampton
4            4 2000-08-19       Leeds        Everton
...        ...        ...         ...            ...
45378    49493 2000-05-13       Nancy        Auxerre
45379    49494 2000-05-13      Rennes           Metz
45380    49495 2000-05-13       Sedan      Marseille
45381    49496 2000-05-13  St Etienne         Monaco
45382    49497 2000-05-13      Troyes       Paris SG

[45383 rows x 4 columns]

In [11]:
df_concat

,Div,Date,HomeTeam,AwayTeam,FTR,B365D,B365H,B365A,res
0,D1,2004-08-06,Werder Bremen,Schalke 04,H,3.25,1.90,3.50,1
1,D1,2004-08-07,Dortmund,Wolfsburg,A,3.40,1.57,5.50,2
2,D1,2004-08-07,Freiburg,Hansa Rostock,D,3.25,2.10,3.00,0
3,D1,2004-08-07,Hamburg,Bayern Munich,A,3.25,3.25,2.00,2
4,D1,2004-08-07,Hertha,Bochum,D,3.25,1.83,3.75,0
...,...,...,...,...,...,...,...,...,...
38540,SP2,2021-05-09,Oviedo,Sabadell,H,3.10,1.80,5.00,1
38541,SP2,2021-05-09,Cartagena,Castellon,H,3.10,2.05,3.75,1
38542,SP2,2021-05-09,Logrones,Girona,A,2.80,3.30,2.45,2
38543,SP2,2021-05-10,Vallecano,Leganes,D,2.87,2.40,3.25,0
38544,SP2,2021-05-10,Sp Gijon,Lugo,H,3.10,1.80,5.25,1

In [12]:
df_concat = df_concat.merge(raw_Data, on=['Date','HomeTeam','AwayTeam'])
df_concat

,Div,Date,HomeTeam,AwayTeam,FTR,B365D,B365H,B365A,res,matchId
0,D1,2004-08-06,Werder Bremen,Schalke 04,H,3.25,1.90,3.50,1,22443
1,D1,2004-08-07,Dortmund,Wolfsburg,A,3.40,1.57,5.50,2,22444
2,D1,2004-08-07,Freiburg,Hansa Rostock,D,3.25,2.10,3.00,0,22445
3,D1,2004-08-07,Hamburg,Bayern Munich,A,3.25,3.25,2.00,2,22446
4,D1,2004-08-07,Hertha,Bochum,D,3.25,1.83,3.75,0,22447
...,...,...,...,...,...,...,...,...,...,...
31152,SP1,2021-05-22,Osasuna,Sociedad,A,4.33,5.00,1.61,2,18306
31153,SP1,2021-05-22,Real Madrid,Villarreal,H,5.00,1.40,6.50,1,18307
31154,SP1,2021-05-22,Valladolid,Ath Madrid,A,5.25,9.00,1.33,2,18308
31155,SP1,2021-05-23,Granada,Getafe,D,3.40,2.62,2.60,0,18309
31156,SP1,2021-05-23,Sevilla,Alaves,H,4.33,1.50,6.50,1,18310

In [13]:
df_concat['draw_pred'] = 1/df_concat.B365D
df_concat['home_pred'] = 1/df_concat.B365H
df_concat['away_pred'] = 1/df_concat.B365A
df_concat['label'] = df_concat.res

df_concat

,Div,Date,HomeTeam,AwayTeam,FTR,B365D,B365H,B365A,res,matchId,draw_pred,home_pred,away_pred,label
0,D1,2004-08-06,Werder Bremen,Schalke 04,H,3.25,1.90,3.50,1,22443,0.307692,0.526316,0.285714,1
1,D1,2004-08-07,Dortmund,Wolfsburg,A,3.40,1.57,5.50,2,22444,0.294118,0.636943,0.181818,2
2,D1,2004-08-07,Freiburg,Hansa Rostock,D,3.25,2.10,3.00,0,22445,0.307692,0.476190,0.333333,0
3,D1,2004-08-07,Hamburg,Bayern Munich,A,3.25,3.25,2.00,2,22446,0.307692,0.307692,0.500000,2
4,D1,2004-08-07,Hertha,Bochum,D,3.25,1.83,3.75,0,22447,0.307692,0.546448,0.266667,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31152,SP1,2021-05-22,Osasuna,Sociedad,A,4.33,5.00,1.61,2,18306,0.230947,0.200000,0.621118,2
31153,SP1,2021-05-22,Real Madrid,Villarreal,H,5.00,1.40,6.50,1,18307,0.200000,0.714286,0.153846,1
31154,SP1,2021-05-22,Valladolid,Ath Madrid,A,5.25,9.00,1.33,2,18308,0.190476,0.111111,0.751880,2
31155,SP1,2021-05-23,Granada,Getafe,D,3.40,2.62,2.60,0,18309,0.294118,0.381679,0.384615,0
31156,SP1,2021-05-23,Sevilla,Alaves,H,4.33,1.50,6.50,1,18310,0.230947,0.666667,0.153846,1

In [14]:
df_concat['prediction'] = df_concat[['draw_pred','home_pred','away_pred']].to_numpy().argmax(axis=1)

In [17]:
df_concat[['matchId','draw_pred','home_pred','away_pred','prediction','label']].to_csv(path_raw + 'bets.csv',sep=';',decimal=',')